### ISSUE TITLE
Finalize migration of schema docs

### ISSUE THREAD

**Issue by mikeal** [ipld/docs#6]
I’ve copied over the schema docs but I need you to go over them, make sure they are accurate, and take down the old docs so that we don’t have them in two places.

**Comment by rvagg** [comment]
hm, this is going to be tricky, because they still need a "spec", might need to write something from scratch around schema-schema in the specs repo to handle that.

**Comment by rvagg** [comment]
7068a17ee5dc4ed533afd9103054deb628936c6e

Deleted from here and linked back to there, do you want to leave them on the specs site for now @mikeal?

**Comment by mikeal** [comment]
Ya, this was too much work to migrate in this initial release of the docs site.
